package com.example.application.views.rsp;

import com.example.application.data.SamplePerson;
import com.example.application.services.SamplePersonService;
import com.example.application.views.MainLayout;
import com.vaadin.flow.component.Composite;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.button.ButtonVariant;
import com.vaadin.flow.component.dependency.Uses;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.html.H3;
import com.vaadin.flow.component.icon.Icon;
import com.vaadin.flow.component.orderedlayout.FlexComponent;
import com.vaadin.flow.component.orderedlayout.FlexComponent.Alignment;
import com.vaadin.flow.component.orderedlayout.FlexComponent.JustifyContentMode;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.progressbar.ProgressBar;
import com.vaadin.flow.component.tabs.Tab;
import com.vaadin.flow.component.tabs.Tabs;
import com.vaadin.flow.component.textfield.TextArea;
import com.vaadin.flow.component.timepicker.TimePicker;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.spring.data.VaadinSpringDataHelpers;
import com.vaadin.flow.theme.lumo.LumoUtility.Gap;
import com.vaadin.flow.theme.lumo.LumoUtility.Padding;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.PageRequest;

@PageTitle("RSP")
@Route(value = "my-view", layout = MainLayout.class)
@Uses(Icon.class)
public class RSPView extends Composite<VerticalLayout> {

    public RSPView() {
        HorizontalLayout layoutRow = new HorizontalLayout();
        Button buttonPrimary = new Button();
        Button buttonPrimary2 = new Button();
        Button buttonPrimary3 = new Button();
        Button buttonPrimary4 = new Button();
        Button buttonPrimary5 = new Button();
        HorizontalLayout layoutRow2 = new HorizontalLayout();
        HorizontalLayout layoutRow3 = new HorizontalLayout();
        H3 h3 = new H3();
        ProgressBar progressBar = new ProgressBar();
        HorizontalLayout layoutRow4 = new HorizontalLayout();
        VerticalLayout layoutColumn2 = new VerticalLayout();
        H3 h32 = new H3();
        VerticalLayout layoutColumn3 = new VerticalLayout();
        H3 h33 = new H3();
        Grid multiSelectGrid = new Grid(SamplePerson.class);
        HorizontalLayout layoutRow5 = new HorizontalLayout();
        Tabs tabs = new Tabs();
        TimePicker timePicker = new TimePicker();
        VerticalLayout layoutColumn4 = new VerticalLayout();
        H3 h34 = new H3();
        TextArea textArea = new TextArea();
        HorizontalLayout layoutRow6 = new HorizontalLayout();
        Button buttonPrimary6 = new Button();
        TimePicker timePicker2 = new TimePicker();
        Button buttonPrimary7 = new Button();
        H3 h35 = new H3();
        HorizontalLayout layoutRow7 = new HorizontalLayout();
        HorizontalLayout layoutRow8 = new HorizontalLayout();
        getContent().setWidth("100%");
        getContent().getStyle().set("flex-grow", "1");
        layoutRow.setWidthFull();
        getContent().setFlexGrow(1.0, layoutRow);
        layoutRow.addClassName(Gap.MEDIUM);
        layoutRow.setWidth("100%");
        layoutRow.setHeight("40px");
        buttonPrimary.setText("Event 1");
        buttonPrimary.setWidth("min-content");
        buttonPrimary.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        buttonPrimary2.setText("Event 2");
        layoutRow.setAlignSelf(FlexComponent.Alignment.START, buttonPrimary2);
        buttonPrimary2.setWidth("min-content");
        buttonPrimary2.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        buttonPrimary3.setText("Event 3");
        buttonPrimary3.setWidth("min-content");
        buttonPrimary3.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        buttonPrimary4.setText("Event 4");
        buttonPrimary4.setWidth("min-content");
        buttonPrimary4.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        buttonPrimary5.setText("Event 5");
        buttonPrimary5.setWidth("min-content");
        buttonPrimary5.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        layoutRow2.addClassName(Gap.MEDIUM);
        layoutRow2.setWidth("100%");
        layoutRow2.setHeight("300px");
        layoutRow3.setHeightFull();
        layoutRow2.setFlexGrow(1.0, layoutRow3);
        layoutRow3.addClassName(Gap.MEDIUM);
        layoutRow3.setWidth("100%");
        layoutRow3.setHeight("250px");
        h3.setText("Input Stream");
        h3.setWidth("max-content");
        progressBar.setValue(0.5);
        layoutRow4.addClassName(Gap.MEDIUM);
        layoutRow4.setWidth("100%");
        layoutRow4.setHeight("500px");
        layoutColumn2.setWidth("1000px");
        layoutColumn2.setHeight("500px");
        h32.setText("Snapshot Graph");
        h32.setWidth("max-content");
        layoutColumn3.setHeightFull();
        layoutRow4.setFlexGrow(1.0, layoutColumn3);
        layoutColumn3.setWidth("1000px");
        layoutColumn3.setHeight("500px");
        h33.setText("Time Varying Table");
        h33.setWidth("max-content");
        multiSelectGrid.setSelectionMode(Grid.SelectionMode.MULTI);
        multiSelectGrid.setWidth("100%");
        multiSelectGrid.getStyle().set("flex-grow", "0");
        setGridSampleData(multiSelectGrid);
        layoutRow5.setWidthFull();
        layoutColumn3.setFlexGrow(1.0, layoutRow5);
        layoutRow5.addClassName(Gap.XLARGE);
        layoutRow5.setWidth("100%");
        layoutRow5.getStyle().set("flex-grow", "1");
        layoutRow5.setAlignItems(Alignment.CENTER);
        layoutRow5.setJustifyContentMode(JustifyContentMode.CENTER);
        tabs.setWidth("400px");
        setTabsSampleData(tabs);
        timePicker.setLabel("Time picker");
        timePicker.setWidth("min-content");
        layoutColumn4.setHeightFull();
        layoutRow4.setFlexGrow(1.0, layoutColumn4);
        layoutColumn4.setWidth("100%");
        layoutColumn4.getStyle().set("flex-grow", "1");
        h34.setText("Querying");
        h34.setWidth("max-content");
        textArea.setLabel("Text area");
        textArea.setWidth("100%");
        textArea.setHeight("200px");
        layoutRow6.setWidthFull();
        layoutColumn4.setFlexGrow(1.0, layoutRow6);
        layoutRow6.addClassName(Gap.MEDIUM);
        layoutRow6.setWidth("100%");
        layoutRow6.getStyle().set("flex-grow", "1");
        buttonPrimary6.setText("Start");
        layoutRow6.setAlignSelf(FlexComponent.Alignment.CENTER, buttonPrimary6);
        buttonPrimary6.setWidth("min-content");
        buttonPrimary6.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        timePicker2.setLabel("Time picker");
        layoutRow6.setAlignSelf(FlexComponent.Alignment.CENTER, timePicker2);
        timePicker2.setWidth("min-content");
        timePicker2.setHeight("100px");
        buttonPrimary7.setText("Stop");
        layoutRow6.setAlignSelf(FlexComponent.Alignment.CENTER, buttonPrimary7);
        buttonPrimary7.setWidth("min-content");
        buttonPrimary7.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        h35.setText("Output Stream");
        h35.setWidth("max-content");
        layoutRow7.addClassName(Gap.MEDIUM);
        layoutRow7.addClassName(Padding.MEDIUM);
        layoutRow7.setWidth("100%");
        layoutRow7.setHeight("100px");
        layoutRow7.setAlignItems(Alignment.CENTER);
        layoutRow7.setJustifyContentMode(JustifyContentMode.START);
        layoutRow8.setHeightFull();
        layoutRow7.setFlexGrow(1.0, layoutRow8);
        layoutRow8.addClassName(Gap.MEDIUM);
        layoutRow8.setWidth("100%");
        layoutRow8.getStyle().set("flex-grow", "1");
        getContent().add(layoutRow);
        layoutRow.add(buttonPrimary);
        layoutRow.add(buttonPrimary2);
        layoutRow.add(buttonPrimary3);
        layoutRow.add(buttonPrimary4);
        layoutRow.add(buttonPrimary5);
        getContent().add(layoutRow2);
        layoutRow2.add(layoutRow3);
        layoutRow3.add(h3);
        getContent().add(progressBar);
        getContent().add(layoutRow4);
        layoutRow4.add(layoutColumn2);
        layoutColumn2.add(h32);
        layoutRow4.add(layoutColumn3);
        layoutColumn3.add(h33);
        layoutColumn3.add(multiSelectGrid);
        layoutColumn3.add(layoutRow5);
        layoutRow5.add(tabs);
        layoutRow5.add(timePicker);
        layoutRow4.add(layoutColumn4);
        layoutColumn4.add(h34);
        layoutColumn4.add(textArea);
        layoutColumn4.add(layoutRow6);
        layoutRow6.add(buttonPrimary6);
        layoutRow6.add(timePicker2);
        layoutRow6.add(buttonPrimary7);
        getContent().add(h35);
        getContent().add(layoutRow7);
        layoutRow7.add(layoutRow8);
    }

    private void setGridSampleData(Grid grid) {
        grid.setItems(query -> samplePersonService.list(
                PageRequest.of(query.getPage(), query.getPageSize(), VaadinSpringDataHelpers.toSpringDataSort(query)))
                .stream());
    }

    @Autowired()
    private SamplePersonService samplePersonService;

    private void setTabsSampleData(Tabs tabs) {
        tabs.add(new Tab("Dashboard"));
        tabs.add(new Tab("Payment"));
        tabs.add(new Tab("Shipping"));
    }
}
